services:
  - type: web
    name: telegram-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: TELEGRAM_TOKEN
        value: TU_TOKEN_DE_BOT
      - key: SUPABASE_URL
        value: https://tuproyecto.supabase.co
      - key: SUPABASE_ANON_KEY
        value: clave_publica_de_supabase
